### ISSUE TITLE
Don't hardcode zumobi into commit links

### ISSUE THREAD

**Issue by knodi** [epinault/cruisecontrolrb-to-slack#5]
See here:
https://github.com/epinault/cruisecontrolrb-to-slack/blob/master/lib/cruisecontrolrb-to-slack/cruisecontrolrb.rb#L46

This tool should be able to infer git repo more accurately, perhaps by using shell commands in the work directory, or using some other approach.

**Comment by epinault** [comment]
Yea, I was hoping to extract that logic at some point to better detect but then we moved to Jenkins as Cruisecontrol is pretty much unmaintained last I checked https://github.com/thoughtworks/cruisecontrol.rb/issues/134
